# Make sure to check the documentation at http://goreleaser.com
dist: build/dist

before:
  hooks:
    - ./cicd/prepare.sh
builds:
- 
  main: ./caddy/main.go
  env:
    - CGO_ENABLED=0
    - GO111MODULE=off
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    - -extldflags "-static"
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    # - 386
  hooks:
    # pre: rice embed-go
    # post: ./script.sh
archive:
  # replacements:
  #   darwin: Darwin
  #   linux: Linux
  #   windows: Windows
  #   386: i386
  #   amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
